Dev
IgorAleksandroff/gophermart pull request #2
Opened 2022-11-17 17:31 UTC by IgorAleksandroff

2022-11-21 16:46 UTC, tmvrus requested changes
Есть небольшие недочеты

2022-11-21 16:46 UTC, tmvrus commented on internal/repository/postgres.go
> +	repositoryPG := pgRep{ctx: context.Background(), db: db, l: log}
Контекст должен быть индивидуальный на каждый запрос, пробрасывать его надо, в нашем случае, их кода. который вызывает методы storage-layer

2022-11-21 16:46 UTC, tmvrus commented on internal/repository/postgres.go
> +			id serial,
id serial в этих таблицах лишний, поскольку уже есть primary key

2022-11-21 16:46 UTC, tmvrus commented on internal/repository/postgres.go
> +		    SET (user_login, status, accrual, uploaded_at) = (EXCLUDED.user_login, EXCLUDED.status, EXCLUDED.accrual, EXCLUDED.uploaded_at)`
user_login это внешний ключ "создателя" заказа, по бизнес-логике обновляться/изменятся он не может

2022-11-21 16:46 UTC, tmvrus commented on internal/repository/postgres.go
> +	_, err := p.db.ExecContext(p.ctx, querySaveWithdrawn,
случай с конфликтом записи не обрабатывается, это может привести к ошибке

2022-11-27 20:20 UTC, IgorAleksandroff commented on internal/repository/postgres.go
> +	repositoryPG := pgRep{ctx: context.Background(), db: db, l: log}
пробросил контекст

2022-11-27 20:21 UTC, IgorAleksandroff commented on internal/repository/postgres.go
> +			id serial,
почистил

2022-11-27 20:21 UTC, IgorAleksandroff commented on internal/repository/postgres.go
> +		    SET (user_login, status, accrual, uploaded_at) = (EXCLUDED.user_login, EXCLUDED.status, EXCLUDED.accrual, EXCLUDED.uploaded_at)`
сделал login внешним ключом

2022-11-27 20:22 UTC, IgorAleksandroff commented on internal/repository/postgres.go
> +	_, err := p.db.ExecContext(p.ctx, querySaveWithdrawn,
сделал проверку записи

2022-12-01 08:48 UTC, tmvrus approved these changes

2022-12-01 08:48 UTC, tmvrus commented on internal/repository/postgres.go
> +			login VARCHAR(64) PRIMARY KEY,
id можно не добавлять, есть login который уже первичный ключ

2022-12-01 08:48 UTC, tmvrus commented on internal/repository/postgres.go
> +			password VARCHAR(128),
password тоже  хорошо бы сделать NOT NULL

2022-12-01 08:48 UTC, tmvrus commented on internal/repository/postgres.go
> +			status VARCHAR(32) NOT NULL,
для ограниченного набора значений в постгресе есть специальный enum type

2022-12-01 08:48 UTC, tmvrus commented on internal/repository/postgres.go
> +	once.Do(func() {
спорное использование once.Do, если я захочу воздать два разных подключения к разным базам, текущая реализация мне этого не позволит

2022-12-05 17:24 UTC, IgorAleksandroff commented on internal/repository/postgres.go
> +			login VARCHAR(64) PRIMARY KEY,
проглядел(

2022-12-05 17:26 UTC, IgorAleksandroff commented on internal/repository/postgres.go
> +			status VARCHAR(32) NOT NULL,
добавил enum, действительно так лучше.

2022-12-05 17:28 UTC, IgorAleksandroff commented on internal/repository/postgres.go
> +	once.Do(func() {
согласен, не уместно. Правда пришлось переиспользовать репозиторий для воркера, иначе панику ловил при втором подключении, так и не понял почему.

2022-12-05 17:28 UTC, merged